/**
 * @file Exact-reason cases for the intro guard: review quotes, normalization and paraphrases.
 */
import { describe, expect, it } from 'vitest';

import { guardIntro, GuardReason } from './output.guard';

/** Every sentence quoted in review rounds 1 and 2, normalization cases and adversarial paraphrases, with exact reasons. */
const EXACT: readonly (readonly [string, readonly GuardReason[]])[] = [
  ['You are able to take Calculus II.', [GuardReason.AcademicAction]],
  ['You can still take Calculus II.', [GuardReason.AcademicAction]],
  ['You may take Calculus II.', [GuardReason.AcademicAction]],
  ['Nothing stops you from taking Calculus II.', [GuardReason.AcademicAction]],
  ["You're in Calculus II.", [GuardReason.AcademicAction]],
  ['Your plan is final.', [GuardReason.AcademicAction]],
  ['You can\u2019t sign up for that class.', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['You can\u2019t take that course.', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['You got a B in Biology.', [GuardReason.CreditOrGrade]],
  ['Classes end in May.', [GuardReason.DateOrDeadline, GuardReason.AcademicAction]],
  ['eli\u200bgible', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['regis\u00adtered', [GuardReason.EnrollmentStatus, GuardReason.AcademicAction]],
  ['You are \u0410 student', [GuardReason.NonAscii]],
  ['You got a B\u0430', [GuardReason.NonAscii, GuardReason.CreditOrGrade]],
  ['Take it in year \uff13', [GuardReason.AcademicAction, GuardReason.Digit]],
  ['You can\u2019t take it', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['You\u00a0can\u00a0take it', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['caf\u00e9 plan', [GuardReason.NonAscii]],
  ['Calculus II is open to you.', [GuardReason.DateOrDeadline]],
  ['Go ahead and pick Calculus II.', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  [
    'That class is fine for you.',
    [GuardReason.Eligibility, GuardReason.Readiness, GuardReason.AcademicAction],
  ],
  ['You have what it takes for Calculus II.', [GuardReason.AcademicAction]],
  ['Calculus II works for you.', [GuardReason.Eligibility]],
  ['Nothing stands in your way.', [GuardReason.Eligibility]],
  ['You are good for Calculus II.', [GuardReason.Readiness]],
  ['Feel free to go for Calculus II.', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['Calculus II is yours.', [GuardReason.Eligibility]],
  ['You meet the bar.', [GuardReason.MetOrSatisfied]],
  ['You clear the bar for it.', [GuardReason.Eligibility]],
  ['That course is on the table for you.', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['No problem with that class.', [GuardReason.Eligibility, GuardReason.AcademicAction]],
  ['You have the background for it.', [GuardReason.Eligibility]],
  ['You are covered for Calculus II.', [GuardReason.Eligibility]],
  ['Calculus II is a good fit.', [GuardReason.Readiness]],
  ['Go for Calculus II.', [GuardReason.AcademicAction]],
  ['You belong in Calculus II.', [GuardReason.AcademicAction]],
  ['You have access to Calculus II.', [GuardReason.AcademicAction]],
  ['Calculus II is available.', [GuardReason.AcademicAction]],
  ['Yes, go for it.', [GuardReason.AcademicAction]],
  ['Approved.', [GuardReason.EnrollmentStatus]],
  ['Looks like a yes.', [GuardReason.AcademicAction]],
  ['Your plan is saved and good.', [GuardReason.Readiness, GuardReason.EnrollmentStatus]],
  ['You are signed in to Calculus II.', [GuardReason.EnrollmentStatus]],
  ['Your schedule is locked.', [GuardReason.EnrollmentStatus]],
  ['It is on your schedule.', [GuardReason.EnrollmentStatus]],
  ['Everything is in place.', [GuardReason.MetOrSatisfied]],
  ['Your spot is held.', [GuardReason.EnrollmentStatus]],
  ['The plan went through.', [GuardReason.EnrollmentStatus]],
  ['That is booked.', [GuardReason.EnrollmentStatus]],
  ['Consider it handled.', [GuardReason.MetOrSatisfied, GuardReason.EnrollmentStatus]],
  ['It is submitted.', [GuardReason.EnrollmentStatus]],
  ['The change was made.', [GuardReason.EnrollmentStatus]],
  ['Your courses are in.', [GuardReason.EnrollmentStatus, GuardReason.AcademicAction]],
  ['The seat is yours.', [GuardReason.Eligibility, GuardReason.EnrollmentStatus]],
  ['You made it into the class.', [GuardReason.AcademicAction]],
  ['Your name is on the roster.', [GuardReason.AcademicAction]],
  ['The system has you down.', [GuardReason.EnrollmentStatus]],
  ['You hold a place.', [GuardReason.EnrollmentStatus]],
  ['Your request went in.', [GuardReason.EnrollmentStatus]],
  ['Calculus II is part of your plan now.', [GuardReason.EnrollmentStatus]],
  ['You did well in Biology.', [GuardReason.Readiness]],
  ['Your average is high.', [GuardReason.CreditOrGrade]],
  ['You earned top marks.', [GuardReason.CreditOrGrade]],
  ['That is worth three.', [GuardReason.CreditOrGrade]],
  ['You scored high on it.', [GuardReason.CreditOrGrade]],
  ['Your standing is strong.', [GuardReason.Readiness]],
  [
    'Your transcript looks good.',
    [GuardReason.CreditOrGrade, GuardReason.MetOrSatisfied, GuardReason.Readiness],
  ],
  ['That is a full load.', [GuardReason.CreditOrGrade]],
  [
    'You are one class short.',
    [GuardReason.CreditOrGrade, GuardReason.MetOrSatisfied, GuardReason.AcademicAction],
  ],
  ['You have enough for it.', [GuardReason.MetOrSatisfied]],
  ['Twelve is a full load.', [GuardReason.CreditOrGrade]],
  ['You aced it.', [GuardReason.Readiness]],
  [
    'Your mark was excellent.',
    [GuardReason.CreditOrGrade, GuardReason.Readiness, GuardReason.AcademicAction],
  ],
  ['Your result was great.', [GuardReason.CreditOrGrade, GuardReason.Readiness]],
  ['You excelled.', [GuardReason.AcademicAction]],
  ['You are a senior.', [GuardReason.AcademicAction]],
  ['Half your degree is behind you.', [GuardReason.AcademicAction]],
  ['Your degree is nearly there.', [GuardReason.Readiness, GuardReason.AcademicAction]],
  ['You are close to finishing.', [GuardReason.Readiness, GuardReason.DateOrDeadline]],
  ['You are set for next term.', [GuardReason.Readiness, GuardReason.DateOrDeadline]],
  ['Nothing is missing.', [GuardReason.MetOrSatisfied]],
  ['You have everything needed.', [GuardReason.MetOrSatisfied]],
  ['The checks look good.', [GuardReason.MetOrSatisfied, GuardReason.Readiness]],
  ['All clear.', [GuardReason.MetOrSatisfied]],
  ['It looks fine.', [GuardReason.MetOrSatisfied, GuardReason.Readiness]],
  ['This works out.', [GuardReason.MetOrSatisfied]],
  ['You are in good shape.', [GuardReason.Readiness, GuardReason.AcademicAction]],
  ['That is sorted.', [GuardReason.MetOrSatisfied]],
  ['Nothing to worry about.', [GuardReason.MetOrSatisfied, GuardReason.Readiness]],
  ['The plan is solid.', [GuardReason.Readiness]],
  ['No issues found.', [GuardReason.MetOrSatisfied]],
  ['You have until Friday.', [GuardReason.DateOrDeadline]],
  ['Apply before the window shuts.', [GuardReason.EnrollmentStatus]],
  ['There is still time.', [GuardReason.EnrollmentStatus]],
  ['The cutoff passed.', [GuardReason.PassFail, GuardReason.DateOrDeadline]],
  ['Act quickly.', [GuardReason.EnrollmentStatus]],
  ['It is too late now.', [GuardReason.EnrollmentStatus]],
  ['Do it this week.', [GuardReason.DateOrDeadline]],
  ['Hurry before it is gone.', [GuardReason.EnrollmentStatus]],
  ['Time is running out.', [GuardReason.EnrollmentStatus]],
  ['The period is over.', [GuardReason.EnrollmentStatus]],
  ['Do it right away.', [GuardReason.EnrollmentStatus]],
  ['Submit it at once.', [GuardReason.EnrollmentStatus]],
  ['Come by the fall opening.', [GuardReason.EnrollmentStatus]],
  [
    'Registration ends Friday.',
    [GuardReason.DateOrDeadline, GuardReason.EnrollmentStatus, GuardReason.AcademicAction],
  ],
  ['It expires tonight.', [GuardReason.DateOrDeadline]],
  ['An advisor will look at it.', [GuardReason.AdvisorPromise]],
  ['Staff will take a look.', [GuardReason.AdvisorPromise, GuardReason.AcademicAction]],
  ['Someone is looking into it.', [GuardReason.AdvisorPromise]],
  ['We will follow up.', [GuardReason.AdvisorPromise]],
  ['Your case has been sent.', [GuardReason.EnrollmentStatus, GuardReason.AdvisorPromise]],
  ['They will be in contact.', [GuardReason.AdvisorPromise]],
  ['The office will get in touch.', [GuardReason.AdvisorPromise, GuardReason.AcademicAction]],
  ['Help is on the way.', [GuardReason.AdvisorPromise]],
  ['Your request is with the team.', [GuardReason.AdvisorPromise]],
  ['Expect a call.', [GuardReason.AdvisorPromise]],
  ['You will hear from us.', [GuardReason.AdvisorPromise]],
  ['A counselor will check in.', [GuardReason.CreditOrGrade, GuardReason.AdvisorPromise]],
  ['Your advisor knows.', [GuardReason.AdvisorPromise]],
  ['The advising office got it.', [GuardReason.AdvisorPromise]],
  ['Message delivered to staff.', [GuardReason.AdvisorPromise]],
  ['Email your advisor.', [GuardReason.AdvisorPromise]],
];

describe('guardIntro exact reasons', () => {
  it.each(EXACT)('rejects with exact reasons: %s', (text, reasons) => {
    expect(guardIntro(text)).toEqual({ ok: false, reasons });
  });
});
